// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgLfEsJU2Qvi-LQbrhAE9sm15cWsejRTw',
    appId: '1:228913782377:web:88159814464b0631fa0cf8',
    messagingSenderId: '228913782377',
    projectId: 'weather-forcast-dev',
    authDomain: 'weather-forcast-dev.firebaseapp.com',
    storageBucket: 'weather-forcast-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxhad-TUNKFwxhXcxsarebHlROPBm9f_s',
    appId: '1:228913782377:android:f21fa51c844a8479fa0cf8',
    messagingSenderId: '228913782377',
    projectId: 'weather-forcast-dev',
    storageBucket: 'weather-forcast-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAbbcL4dXEiaODu8se3IsTn_5Pjtg2LEM',
    appId: '1:228913782377:ios:3394c7a38f732f85fa0cf8',
    messagingSenderId: '228913782377',
    projectId: 'weather-forcast-dev',
    storageBucket: 'weather-forcast-dev.firebasestorage.app',
    iosBundleId: 'com.example.gorouter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAbbcL4dXEiaODu8se3IsTn_5Pjtg2LEM',
    appId: '1:228913782377:ios:3394c7a38f732f85fa0cf8',
    messagingSenderId: '228913782377',
    projectId: 'weather-forcast-dev',
    storageBucket: 'weather-forcast-dev.firebasestorage.app',
    iosBundleId: 'com.example.gorouter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgLfEsJU2Qvi-LQbrhAE9sm15cWsejRTw',
    appId: '1:228913782377:web:374e8a9da4cd187cfa0cf8',
    messagingSenderId: '228913782377',
    projectId: 'weather-forcast-dev',
    authDomain: 'weather-forcast-dev.firebaseapp.com',
    storageBucket: 'weather-forcast-dev.firebasestorage.app',
  );
}
